// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vydoclvjdihbrhkuohun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5ZG9jbHZqZGloYnJoa3VvaHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDYyMjYsImV4cCI6MjA2NTE4MjIyNn0.j1b0sv_xTD5keCb9t1VvZg1IWqYzRt5I0-GvbiZbTig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);