
-- Mise à jour de la table books avec tous les livres du professeur
-- D'abord, nous allons vider la table existante et insérer tous les nouveaux livres
DELETE FROM books;

-- Réinitialiser la séquence d'ID
ALTER SEQUENCE books_id_seq RESTART WITH 1;

-- Insérer tous les livres du professeur avec leurs informations complètes
INSERT INTO books (title, title_en, year, publisher, publisher_en, genre, genre_en, description, description_en, image_url, price, stock_quantity, featured, active) VALUES
('Entre Mythes et Modernités : Aspects de la poésie négro-africaine d''expression française', 'Between Myths and Modernities: Aspects of French-language Negro-African poetry', 1998, 'Editions du Septentrion', 'Septentrion Publishing', 'Essai', 'Essay', 'Une analyse approfondie de la poésie négro-africaine d''expression française, explorant les tensions entre traditions mythiques et aspirations modernes.', 'An in-depth analysis of French-language Negro-African poetry, exploring tensions between mythical traditions and modern aspirations.', '/lovable-uploads/f35c927d-b277-4b96-b988-45b75303d0ee.png', 25000, 10, true, true),

('Créations burlesques et Déconstruction chez Ken Bugul', 'Burlesque Creations and Deconstruction in Ken Bugul', 2001, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Une étude littéraire sur les techniques burlesques et déconstructivistes dans l''œuvre de Ken Bugul.', 'A literary study on burlesque and deconstructive techniques in Ken Bugul''s work.', '', 15000, 8, false, true),

('Ce Regard de la Mer… Anthologie de la poésie béninoise d''aujourd''hui', 'This Gaze from the Sea... Anthology of Today''s Beninese Poetry', 2001, 'Les Editions des Diasporas', 'Diasporas Publications', 'Anthologie', 'Anthology', 'Une collection soigneusement sélectionnée de la poésie béninoise contemporaine, reflétant la diversité et la richesse de l''expression poétique du Bénin.', 'A carefully selected collection of contemporary Beninese poetry, reflecting the diversity and richness of Benin''s poetic expression.', '', 18000, 12, false, true),

('Introduction à une poétique du Fa', 'Introduction to a Poetics of Fa', 2006, 'Editions des Diasporas/Editions du Flamboyant', 'Diasporas/Flamboyant Publications', 'Essai', 'Essay', 'Une exploration de la poétique du Fa, système divinatoire et philosophique yoruba, analysant ses dimensions littéraires et spirituelles.', 'An exploration of the poetics of Fa, a Yoruba divinatory and philosophical system, analyzing its literary and spiritual dimensions.', '/lovable-uploads/5ac549c1-30f8-4faf-8b2c-9bd82ba89faa.png', 20000, 15, true, true),

('La petite fille des eaux', 'The Little Girl of the Waters', 2006, 'Edition NDZE', 'NDZE Publishing', 'Roman', 'Novel', 'Un roman collectif explorant les mystères aquatiques et les traditions spirituelles liées à l''eau dans la culture africaine.', 'A collective novel exploring aquatic mysteries and spiritual traditions related to water in African culture.', '', 16000, 6, false, true),

('Les Epouses de Fa', 'The Wives of Fa', 2007, 'L''Harmattan', 'L''Harmattan', 'Récits de la parole sacrée', 'Sacred Word Tales', 'Récits traditionnels révélant les mystères et enseignements du Fa à travers les figures féminines sacrées.', 'Traditional tales revealing the mysteries and teachings of Fa through sacred feminine figures.', '', 18500, 9, false, true),

('Poétique baroque dans les littératures africaines francophones, Tome 1 : Olympe Bhêly-Quenum : Thèmes et Styles', 'Baroque Poetics in Francophone African Literature, Volume 1: Olympe Bhêly-Quenum: Themes and Styles', 2007, 'Edition des Diasporas', 'Diasporas Publishing', 'Essai', 'Essay', 'Analyse stylistique et thématique de l''œuvre d''Olympe Bhêly-Quenum dans le contexte de la poétique baroque africaine.', 'Stylistic and thematic analysis of Olympe Bhêly-Quenum''s work in the context of African baroque poetics.', '', 22000, 7, false, true),

('Pour circoncire le sel', 'To Circumcise Salt', 2009, 'Les Editions de la Rose Bleue', 'Blue Rose Publications', 'Poème', 'Poetry', 'Recueil poétique explorant les thèmes de la purification, de la tradition et de la modernité à travers des métaphores saisissantes.', 'Poetry collection exploring themes of purification, tradition and modernity through striking metaphors.', '', 14000, 11, false, true),

('Si Dieu était une femme… Anthologie de la poésie béninoise d''aujourd''hui', 'If God Were a Woman... Anthology of Today''s Beninese Poetry', 2009, 'Les Editions des Diasporas', 'Diasporas Publications', 'Anthologie', 'Anthology', 'Une anthologie révolutionnaire questionnant les représentations divines à travers la poésie béninoise contemporaine.', 'A revolutionary anthology questioning divine representations through contemporary Beninese poetry.', '', 19000, 8, false, true),

('Introduction à une poétique du Fa (2ème Edition revue et augmentée)', 'Introduction to a Poetics of Fa (2nd Revised and Expanded Edition)', 2010, 'Presses Universitaires de Yaoundé', 'University Press of Yaoundé', 'Essai', 'Essay', 'Version enrichie et mise à jour de l''exploration fondamentale de la poétique du Fa, avec de nouveaux développements théoriques.', 'Enriched and updated version of the fundamental exploration of Fa poetics, with new theoretical developments.', '', 21000, 13, false, true),

('Dieu, cet apprenti-sorcier, suivi de Destin d''un Dieu', 'God, This Sorcerer''s Apprentice, followed by Destiny of a God', 2011, 'L''Harmattan', 'L''Harmattan', 'Théâtre', 'Theater', 'Deux pièces théâtrales questionnant la nature divine et les responsabilités cosmiques dans un style dramatique saisissant.', 'Two theatrical plays questioning divine nature and cosmic responsibilities in a striking dramatic style.', '', 16500, 5, false, true),

('Littératures africaines : Langues et Ecritures', 'African Literatures: Languages and Writings', 2011, 'Abis Editions', 'Abis Editions', 'Essai', 'Essay', 'Étude comprehensive des langues et systèmes d''écriture dans les littératures africaines, analysant leur évolution et impact culturel.', 'Comprehensive study of languages and writing systems in African literatures, analyzing their evolution and cultural impact.', '', 28000, 6, false, true),

('Voix et voies nouvelles de la littérature béninoise', 'New Voices and Paths of Beninese Literature', 2011, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Analyse des tendances émergentes et des nouvelles orientations de la littérature béninoise contemporaine.', 'Analysis of emerging trends and new directions in contemporary Beninese literature.', '', 23000, 9, false, true),

('Yɛku-Mɛnji : Une théologie de la mort dans les œuvres de Fa : Essai d''herméneutique littéraire', 'Yɛku-Mɛnji: A Theology of Death in Fa Works: Essay on Literary Hermeneutics', 2012, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Exploration herméneutique des concepts de mort et de transcendance dans la tradition du Fa.', 'Hermeneutical exploration of concepts of death and transcendence in the Fa tradition.', '', 20000, 7, false, true),

('L''Iroko, l''arbre de vie dans la mystique Vodun', 'The Iroko, Tree of Life in Vodun Mysticism', 2017, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Étude symbolique et spirituelle de l''Iroko dans la tradition Vodun, révélant ses dimensions cosmiques et sacrées.', 'Symbolic and spiritual study of the Iroko in Vodun tradition, revealing its cosmic and sacred dimensions.', '/lovable-uploads/9a4cabd7-18d1-47ff-ad00-b09e76b4d2d8.png', 19500, 12, true, true),

('La naissance de Fa, l''enfant qui parle dans le ventre de sa mère', 'The Birth of Fa, the Child Who Speaks in His Mother''s Womb', 2018, 'Laha Editions', 'Laha Editions', 'Récits de la parole sacrée', 'Sacred Word Tales', 'Récits mystiques sur l''origine du Fa, révélant les mystères de la naissance divine et de la parole sacrée.', 'Mystical tales about the origin of Fa, revealing mysteries of divine birth and sacred speech.', '', 17500, 10, false, true),

('Jogbe, La revue des humanités, No1', 'Jogbe, The Humanities Review, No1', 2018, 'Les Editions des Diasporas', 'Diasporas Publications', 'Revue scientifique', 'Scientific Journal', 'Premier numéro de la revue scientifique Jogbe, dédiée aux humanités et aux recherches sur le Vodun.', 'First issue of the scientific journal Jogbe, dedicated to humanities and Vodun research.', '/lovable-uploads/138cf336-12e6-44f1-bfe7-b27ca4048e1d.png', 15000, 20, false, true),

('Jogbe, La revue des humanités, No2', 'Jogbe, The Humanities Review, No2', 2019, 'Les Editions des Diasporas', 'Diasporas Publications', 'Revue scientifique', 'Scientific Journal', 'Deuxième numéro de Jogbe, explorant les savoirs localisés en Afrique de l''Ouest.', 'Second issue of Jogbe, exploring localized knowledge in West Africa.', '/lovable-uploads/6898414f-5655-422e-a976-6e94c3412237.png', 15000, 18, false, true),

('Les fils de Ra (Nous sommes parents d''âme)', 'The Sons of Ra (We Are Soul Relatives)', 2020, 'Les Editions des Diasporas', 'Diasporas Publications', 'Poème', 'Poetry', 'Recueil poétique explorant les liens spirituels et cosmiques entre les peuples africains et l''Égypte antique.', 'Poetry collection exploring spiritual and cosmic links between African peoples and ancient Egypt.', '', 14500, 8, false, true),

('Pour circoncire le sel (2ème édition)', 'To Circumcise Salt (2nd Edition)', 2020, 'Les Editions des Diasporas', 'Diasporas Publications', 'Poème', 'Poetry', 'Édition révisée et enrichie du recueil poétique emblématique sur la purification et les traditions.', 'Revised and enriched edition of the emblematic poetry collection on purification and traditions.', '', 15000, 14, false, true),

('L''Agitateur des étoiles, Poèmes à Nouréini', 'The Star Agitator, Poems to Nouréini', 2021, 'Les Editions des Diasporas', 'Diasporas Publications', 'Poème', 'Poetry', 'Hommage poétique à Nouréini Tidjani-Serpos, figure majeure de la littérature béninoise.', 'Poetic tribute to Nouréini Tidjani-Serpos, major figure of Beninese literature.', '/lovable-uploads/a4098836-d0ea-49b6-9442-388973f75256.png', 16000, 11, true, true),

('Ecritures, Sociétés et Imaginaire', 'Writings, Societies and Imagination', 2021, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Ouvrage collectif dirigé explorant les relations entre écritures, structures sociales et imaginaires culturels.', 'Collective work exploring relationships between writings, social structures and cultural imaginaries.', '', 26000, 5, false, true),

('Logiques et rationalités dans les traditions africaines', 'Logic and Rationalities in African Traditions', 2021, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Vaste étude dirigée sur les systèmes de pensée et les logiques traditionnelles africaines.', 'Vast directed study on African thought systems and traditional logics.', '', 35000, 3, false, true),

('Le Fá expliqué aux profanes. Epitomé d''Ifá ɔrúnmìlà', 'Fa Explained to the Uninitiated. Epitome of Ifá ɔrúnmìlà', 2022, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Guide accessible pour comprendre les fondements du système divinatoire Ifá et ses enseignements.', 'Accessible guide to understanding the foundations of the Ifá divinatory system and its teachings.', '', 18000, 16, false, true),

('L''Autoréférentialité et son actualité', 'Self-Referentiality and Its Relevance', 2023, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Réflexion philosophique sur l''autoréférentialité dans la pensée contemporaine et les traditions africaines.', 'Philosophical reflection on self-referentiality in contemporary thought and African traditions.', '', 22500, 7, false, true),

('Le Fá, la Gnose Àjɛ́ et la Mécanique quantique', 'Fa, Àjɛ́ Gnosis and Quantum Mechanics', 2023, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Exploration fascinante des parallèles entre la spiritualité africaine traditionnelle et la physique quantique moderne.', 'Fascinating exploration of parallels between traditional African spirituality and modern quantum physics.', '/lovable-uploads/20ff9cd3-e282-4357-9e69-a0d80d9f37ad.png', 19000, 9, true, true),

('La Théologie Vodun. Fondement de la pensée classique Ajǎ-Tádó, suivie de Ainsi parla Ifá. Code Gbɛ̀sù', 'Vodun Theology. Foundation of Classical Ajǎ-Tádó Thought, followed by Thus Spoke Ifá. Gbɛ̀sù Code', 2024, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Ouvrage majeur sur les fondements théologiques du Vodun et les codes sacrés d''Ifá.', 'Major work on the theological foundations of Vodun and the sacred codes of Ifá.', '/lovable-uploads/074418fc-4ae6-449c-aa84-4b5327f930f7.png', 24000, 8, true, true),

('Etudes africaines. Langues et formes de la pensée', 'African Studies. Languages and Forms of Thought', 2024, 'Les Editions des Diasporas', 'Diasporas Publications', 'Essai', 'Essay', 'Somme magistrale sur les langues africaines et leurs modes de conceptualisation du monde.', 'Masterful compendium on African languages and their ways of conceptualizing the world.', '/lovable-uploads/f35c927d-b277-4b96-b988-45b75303d0ee.png', 45000, 4, true, true),

('Le Testateur stellaire. Nouréini TIDJANI-SERPOS - Entretiens et Témoignages', 'The Stellar Testator. Nouréini TIDJANI-SERPOS - Interviews and Testimonies', 2024, 'Les Editions des Diasporas', 'Diasporas Publications', 'Entretiens', 'Interviews', 'Recueil d''entretiens et de témoignages sur Nouréini Tidjani-Serpos, figure emblématique de la littérature béninoise.', 'Collection of interviews and testimonies about Nouréini Tidjani-Serpos, emblematic figure of Beninese literature.', '/lovable-uploads/7410117d-2862-4067-b7db-cc9d1dc21a03.png', 20000, 12, false, true);
